name: Linting & Style Checks
on:
  # This Workflow can be triggered manually
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      - name: Set up Python 3.11
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '.github/workflows/requirements/style.txt'

      - name: Install Python dependencies
        run: |
          pip install -r .github/workflows/requirements/style.txt

      - name: Lint and style checks with black, isort, and flake8
        run: |
          black --diff --check gantry
          isort --diff --check gantry
          flake8 gantry
