name: Unit Tests
on:
  # This Workflow can be triggered manually
  workflow_dispatch:
  workflow_call:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            'requirements.txt'
            '.github/workflows/requirements/unit-tests.txt'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install -r .github/workflows/requirements/unit-tests.txt

      - name: Run Unit Tests with Pytest
        run: |
          python -m pytest gantry
